// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1.DAL.Models;

namespace _1.DAL.Migrations
{
    [DbContext(typeof(VatLieuDbContext))]
    [Migration("20221111183323_ok11122022")]
    partial class ok11122022
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_1.DAL.Models.ChiTietGioHang", b =>
                {
                    b.Property<Guid>("IdCTGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal")
                        .HasColumnName("Đơn Giá");

                    b.Property<int>("SoLuongMua")
                        .HasColumnType("int")
                        .HasColumnName("Số Lượng Mua");

                    b.HasKey("IdCTGioHang");

                    b.ToTable("ChiTietGioHang");
                });
#pragma warning restore 612, 618
        }
    }
}
